// Code generated by ent, DO NOT EDIT.

package follows

const (
	// Label holds the string label denoting the follows type in the database.
	Label = "follows"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFollowedby holds the string denoting the followedby field in the database.
	FieldFollowedby = "followedby"
	// FieldFollower holds the string denoting the follower field in the database.
	FieldFollower = "follower"
	// Table holds the table name of the follows in the database.
	Table = "follows"
)

// Columns holds all SQL columns for follows fields.
var Columns = []string{
	FieldID,
	FieldFollowedby,
	FieldFollower,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FollowedbyValidator is a validator for the "followedby" field. It is called by the builders before save.
	FollowedbyValidator func(int) error
	// FollowerValidator is a validator for the "follower" field. It is called by the builders before save.
	FollowerValidator func(int) error
)
