// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bypepe77/api/ent/follows"
)

// FollowsCreate is the builder for creating a Follows entity.
type FollowsCreate struct {
	config
	mutation *FollowsMutation
	hooks    []Hook
}

// SetFollowedby sets the "followedby" field.
func (fc *FollowsCreate) SetFollowedby(i int) *FollowsCreate {
	fc.mutation.SetFollowedby(i)
	return fc
}

// SetFollower sets the "follower" field.
func (fc *FollowsCreate) SetFollower(i int) *FollowsCreate {
	fc.mutation.SetFollower(i)
	return fc
}

// Mutation returns the FollowsMutation object of the builder.
func (fc *FollowsCreate) Mutation() *FollowsMutation {
	return fc.mutation
}

// Save creates the Follows in the database.
func (fc *FollowsCreate) Save(ctx context.Context) (*Follows, error) {
	var (
		err  error
		node *Follows
	)
	if len(fc.hooks) == 0 {
		if err = fc.check(); err != nil {
			return nil, err
		}
		node, err = fc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FollowsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fc.check(); err != nil {
				return nil, err
			}
			fc.mutation = mutation
			if node, err = fc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(fc.hooks) - 1; i >= 0; i-- {
			if fc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, fc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Follows)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FollowsMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FollowsCreate) SaveX(ctx context.Context) *Follows {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FollowsCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FollowsCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FollowsCreate) check() error {
	if _, ok := fc.mutation.Followedby(); !ok {
		return &ValidationError{Name: "followedby", err: errors.New(`ent: missing required field "Follows.followedby"`)}
	}
	if v, ok := fc.mutation.Followedby(); ok {
		if err := follows.FollowedbyValidator(v); err != nil {
			return &ValidationError{Name: "followedby", err: fmt.Errorf(`ent: validator failed for field "Follows.followedby": %w`, err)}
		}
	}
	if _, ok := fc.mutation.Follower(); !ok {
		return &ValidationError{Name: "follower", err: errors.New(`ent: missing required field "Follows.follower"`)}
	}
	if v, ok := fc.mutation.Follower(); ok {
		if err := follows.FollowerValidator(v); err != nil {
			return &ValidationError{Name: "follower", err: fmt.Errorf(`ent: validator failed for field "Follows.follower": %w`, err)}
		}
	}
	return nil
}

func (fc *FollowsCreate) sqlSave(ctx context.Context) (*Follows, error) {
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (fc *FollowsCreate) createSpec() (*Follows, *sqlgraph.CreateSpec) {
	var (
		_node = &Follows{config: fc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: follows.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: follows.FieldID,
			},
		}
	)
	if value, ok := fc.mutation.Followedby(); ok {
		_spec.SetField(follows.FieldFollowedby, field.TypeInt, value)
		_node.Followedby = value
	}
	if value, ok := fc.mutation.Follower(); ok {
		_spec.SetField(follows.FieldFollower, field.TypeInt, value)
		_node.Follower = value
	}
	return _node, _spec
}

// FollowsCreateBulk is the builder for creating many Follows entities in bulk.
type FollowsCreateBulk struct {
	config
	builders []*FollowsCreate
}

// Save creates the Follows entities in the database.
func (fcb *FollowsCreateBulk) Save(ctx context.Context) ([]*Follows, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Follows, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FollowsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FollowsCreateBulk) SaveX(ctx context.Context) []*Follows {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FollowsCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FollowsCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
