// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Follows is the predicate function for follows builders.
type Follows func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
